[book]
authors = ["Ankitects Pty Ltd and contributors"]
description = "Anki 的常见问题解答。Anki 是一款让学习更容易的抽认卡程序。"
language = "zh-CN"
multilingual = false
src = "src"
title = "Anki 常见问题解答"

[build]
create-missing = true

[output.html]
no-section-label = true
git-repository-url = "https://github.com/open-spaced-repetition/anki-faqs-zh-CN/"
additional-css = ["css/misc.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
# sites that block programmatic access
exclude = [ 'quora\.com', 'reddit.com', 'superuser.com', 'github.com/open-spaced-repetition' ]
